image: docker

stages:
- build

build: &build
  before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
  - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
  - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  stage: build
  tags:
  - docker-socket

build-master:
  <<: *build
  script:
  - docker build -t $CI_REGISTRY_IMAGE:latest .
  only:
  - master
